version: "3.9"
services:
  db:
    image: gakgan/dbpstgrs
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    ports:
      - "5082:5432"
    volumes:
      - ./data-pg:/var/lib/postgresql/data
  be:
    image: gakgan/phy-be:latest
    restart: always
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    links:
      - "db:db"
    ports:
      - "5081:8080"
  fe:
    image: gakgan/phy-fe:latest
    restart: always
    ports:
      - "5080:3000"
