version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    ports:
      - "5082:5432"
    volumes:
      - ./data-pg:/var/lib/postgresql/data
  be:
    image: gakgan/phy-be:latest
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ivanbe.rule=Host(`back-82-202-247-237.nip.io`)"
      - "traefik.http.routers.ivanbe.tls.certresolver=letsencrypt"
      - "traefik.http.services.ivanbe.loadbalancer.server.port=8080"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    links:
      - "db:db"
  fe:
    image: gakgan/phy-fe:latest
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ivanfe.rule=Host(`front-82-202-247-237.nip.io`)"
      - "traefik.http.routers.ivanfe.tls.certresolver=letsencrypt"
      - "traefik.http.services.ivanfe.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
