version: "3.9"
services:
  db:
    image: postgres
    restart: always
    networks:
      - proxy
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    ports:
      - "5082:5432"
    volumes:
      - ./data-pg:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
  pgbackups:
    container_name: Backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    networks:
      - proxy
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB:?err}
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@every 1h30m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
    depends_on:
      db:
        condition: service_healthy
  adminer:
    image: adminer
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ivanad.rule=Host(`adminer-82-202-247-237.nip.io`)"
      - "traefik.http.routers.ivanad.tls.certresolver=letsencrypt"
      - "traefik.http.services.ivanad.loadbalancer.server.port=8080"
    depends_on:
      db:
        condition: service_healthy
  be:
    image: gakgan/phy-be:latest
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ivanbe.rule=Host(`back-82-202-247-237.nip.io`)"
      - "traefik.http.routers.ivanbe.tls.certresolver=letsencrypt"
      - "traefik.http.services.ivanbe.loadbalancer.server.port=8080"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
  fe:
    image: gakgan/phy-fe:latest
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ivanfe.rule=Host(`front-82-202-247-237.nip.io`)"
      - "traefik.http.routers.ivanfe.tls.certresolver=letsencrypt"
      - "traefik.http.services.ivanfe.loadbalancer.server.port=3000"
networks:
  proxy:
    external: true
