version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    ports:
      - "8082:5432"
    volumes:
      - ./data-pg:/var/lib/postgresql/data
  be:
    image: gakgan/phy-be:latest
    restart: always
    ports:
      - "8081:8080"
  fe:
    image: gakgan/phy-fe:latest
    restart: always
    ports:
      - "8080:3000"